### PR TITLE
Add AfriNIC WHOIS query

### PR DESCRIPTION
**Pull request by Ankit-Maity**
Took me a while to find.

### CODE REVIEW

**Comment by whym** [comment]
Is it a well-publicized entrypoint? If it's not made easily accessible on their website, I'd rather not link.

**Comment by Ankit-Maity** [comment]
It is the only way to get WHOIS queries directly from URL. It's not well publicized but it is hosted by them and the information matches to their mainstream querying page, so it should be fine.

**Comment by whym** [comment]
Ok, I agree it's fine at least as a temporary measure. I see the problem now - querying an AFRINIC IP does not give as much as information it should, as pointed out at [1]. It's a known to happen when you stick with the RESTful versions. [2]

I'll add a workaround on it shortly.

[1] http://en.wikipedia.org/wiki/Template_talk:Whois#Template-protected_edit_request_on_16_February_2015
[2] https://pypi.python.org/pypi/ipwhois#rest-http

**Comment by Ankit-Maity** [comment]
My only worry is that are all AfriNIC WHOIS responses like this or just CSTGPON network?

**Comment by whym** [comment]
Prior to 51b6fa83, yes, all queries that should be managed by AfriNIC were sent to RIPEN who cannot give us the values of certain fields. (It lacked city and address etc, IIRC.)

**Pull request merged**
